services:
  avito-test:
    build: ./
    volumes:
      - ./migrations:/app/migrations
    env_file:
      - .env
    container_name: avito_test_app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - avito_test_network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    container_name: avito_test_db
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5431:${DB_PORT}"
    networks:
      - avito_test_network

networks:
  avito_test_network:
